name: Will Fleming's Software blog
title: Will Fleming's Software blog
theme: jekyll-theme-slate
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
url: https://wtfleming.github.io/
redcarpet:
  extensions: ["tables"]
github_username: wtfleming
google_analytics: UA-43114529-1
