name: wtf blog
markdown: redcarpet
highlighter: rouge
permalink: /:year/:month/:day/:title/
name: wtf Blog
description: Software engineering
url: http://wtfleming.github.io/
redcarpet:
  extensions: ["tables"]
