# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [ { name = "tags" } ]

theme = "simple-dev-blog"

generate_feed = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true


# Various slugification strategies, see below for details
# Defaults to everything being a slug
# [slugify]
# paths = "on"
# taxonomies = "on"
# anchors = "on"

[extra]
# Put all your custom variables here

nav = [
  { name = "About", path = "/about/" },
  { name = "Blog", path = "/blog/" }
]

# blog_path = "b"

accent = "#05a081"
accent_light = "#82d0c0"

footer_about = """
"""
